name: ğŸ“‹ GolangCI Checks

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  lint:
    name: ğŸ“‹ GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Git clone the repository
        uses: actions/checkout@v6

      - name: ğŸ“¦ Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ§ª Lint
        run: |
          mise run lint
